# Site settings
title: SomethingSomething
logo: /assets/img/logo.png    
# > this means to ignore newlines until "baseurl:"
description: Therapy through play.
baseurl: "/didactic-spoon" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
remote_theme: cam-l/creative-theme-jekyll

# Build settings
destination: _site
# permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor']
